api_platform:
    title: 'OpenChurch API'
    description: 'An open data initiative.'
    version: '0.0.1'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    graphql:
        enabled: true
        graphiql:
            enabled: true
    oauth:
         enabled: true
         clientId: '1_5dq7vt20314wswgks084wkokgogc0g8s0o0s408sogg40cwsgo'
         clientSecret: '3b8fjoxdah8go4gkcks0ogc44o0cg0okk0wg8gk8sc4cw8ckkk'
