parameters:
  env(ELASTICSEARCH_HOST): "elasticsearch"

api_platform:
  title: openchurch
  version: 2.0.0
  defaults:
    stateless: true
    pagination_client_items_per_page: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
  mapping:
    paths:
      - "%kernel.project_dir%/src/Community/Infrastructure/ApiPlatform/Resource/"
      - "%kernel.project_dir%/src/Place/Infrastructure/ApiPlatform/Resource/"
      - "%kernel.project_dir%/src/Place/Domain/Exception/"
      - "%kernel.project_dir%/src/Community/Domain/Exception/"
      - "%kernel.project_dir%/src/Field/Domain/Exception/"
  elasticsearch:
    hosts: ["%env(ELASTICSEARCH_HOST)%"]
  formats:
    json: ["application/json"]
    jsonld: ["application/ld+json"]
  patch_formats:
    json: ["application/json"]
