framework:
  router:
    # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
    # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
    #default_uri: http://localhost

parameters:
  router.request_context.host: "%host_api%"
  router.request_context.scheme: "http"

when@prod:
  framework:
    router:
      strict_requirements: null
