x-extra_hosts: &default-extra_hosts
  - "openchurch.local:host-gateway"
  - "api.openchurch.local:host-gateway"
  - "admin.openchurch.local:host-gateway"

services:
  db:
    image: mariadb:11.5.2
    container_name: openchurch_db
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - openchurch_db_data:/var/lib/mysql:delegated
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: openchurch
      MYSQL_DATABASE: openchurch
      MYSQL_USER: openchurch
      MYSQL_PASSWORD: openchurch
    networks:
      - app-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  elasticsearch:
    image: elasticsearch:8.16.0
    container_name: openchurch_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enrollment.enabled=true
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # 512mo HEAP
      - ELASTIC_PASSWORD=admin
    healthcheck:
      test: "curl -s -u elastic:$$ELASTIC_PASSWORD -f -X GET localhost:9200/_cluster/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - app-network
    ports:
      - 9200:9200
    volumes:
      - ./openchurch_elasticsearch_data:/usr/share/elasticsearch/data

  backend:
    extra_hosts: *default-extra_hosts
    container_name: openchurch_backend
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - ./usr/local/bin/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint
    ports:
      - 443:443
      - 2019:2019
    depends_on:
      - db
      - redis
      - elasticsearch
    user: root
    networks:
      - app-network
    environment:
      ROLE: api
      SERVER_NAME: "localhost api.openchurch.local admin.openchurch.local"
  cli:
    extra_hosts: *default-extra_hosts
    container_name: openchurch_backend_cli
    command: /usr/sbin/cron -f -l 15
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    environment:
      ROLE: cli
      SERVER_NAME: :80
      ELASTIC_PASSWORD: admin
      ELASTICSEARCH_IRI: http://elastic:admin@elasticsearch:9200
    depends_on:
      - db
      - redis
      - elasticsearch
    user: root
    healthcheck:
      test: if [ $$(pgrep -F /var/run/crond.pid -r S,R --count) -eq 1 ]; then exit 0; else exit 1; fi
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - app-network
  python:
    container_name: openchurch_python
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    depends_on:
      - redis
      - backend
    networks:
      - app-network
    extra_hosts:
      - "api.openchurch.local:host-gateway"
    environment:
      OPENCHURCH_HOST: "https://api.openchurch.local/api"
      PYTHONWARNINGS: "ignore:Unverified HTTPS request"
      SYNCHRO_SECRET_KEY: "secret"
      REDIS_URL: redis://redis:6379
      SLEEP_MS_BETWEEN_REQUESTS: 1
    volumes:
      - ./scripts:/app
  redis:
    image: redis:5
    container_name: openchurch_redis
    expose:
      - 6379
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 1s
      timeout: 5s
      retries: 55
      start_period: 30s

volumes:
  openchurch_db_data: {}
  openchurch_elasticsearch_data: {}

networks:
  app-network:
    driver: bridge
