x-extra_hosts: &default-extra_hosts
  - "openchurch.local:host-gateway"
  - "api.openchurch.local:host-gateway"
  - "admin.openchurch.local:host-gateway"

services:
  db:
    image: mariadb:11.5.2
    container_name: openchurch_db
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - openchurch_db_data:/var/lib/mysql:delegated
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: openchurch
      MYSQL_DATABASE: openchurch
      MYSQL_USER: openchurch
      MYSQL_PASSWORD: openchurch
    networks:
      - app-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  elasticsearch:
    image: elasticsearch:8.16.0
    container_name: openchurch_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enrollment.enabled=true
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # 512mo HEAP
    networks:
      - app-network
    ports:
      - 9200:9200
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/elastic/data

  backend:
    extra_hosts: *default-extra_hosts
    container_name: openchurch_backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./usr/local/bin/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint
    ports:
      - 443:443
      - 2019:2019
    depends_on:
      - db
      - elasticsearch
    user: root
    networks:
      - app-network
    environment:
      SERVER_NAME: localhost api.openchurch.local admin.openchurch.local
      DATABASE_URL: mysql://root:openchurch@db:3306/openchurch?serverVersion=11.5.2-MariaDB&charset=utf8mb4

volumes:
  openchurch_db_data: {}

networks:
  app-network:
    driver: bridge
