types:
    Departement:
        properties:
            code: { range: Text }
            name: { range: Text }
            de: { range: Text }
    Commune:
        properties:
            codeInsee: { range: Text }
            name: { range: Text }
            searchable: { range: Text }
            departement: { range: Departement, cardinality: (*..0) }
            commonsCategory: { range: Text }
            latitude: { range: Number }
            longitude: { range: Number }
    Church:
        properties:
            name: ~
            alternateName: ~
            description: ~
            address: { range: PostalAddress }
            commune: { range: Commune, cardinality: (*..0) }
            departement: { range: Departement, cardinality: (*..0) }
            hasMap: ~
            telephone: ~
            faxNumber: ~
            wikidataId: { range: Text }
            wikidataDioceseId: { range: Text }
            merimeeId: { range: Text }
            egliseInfoId: { range: Text }
            wikipediaId: { range: Text }
            commonsId: { range: Text }
            clochersId: { range: Text }
            patrimoineReligieuxId: { range: Text }
            url: { range: Text }
            geo: { range: GeoCoordinates }
            photo: { range: Text }
            thumbnail: { range: Text, nullable: true }
            logo: { range: Text }
            isAccessibleForFree: ~
            publicAccess: ~
            maximumAttendeeCapacity: ~
            additionalType: ~
            event: { range: Event }
            review: { range: Review }
            openingHours: ~
            openingHoursSpecification: { range: OpeningHoursSpecification }
            specialOpeningHoursSpecification: { range: OpeningHoursSpecification }
            dateCreated: { range: DateTime, nullable: true }
            dateModified: { range: DateTime, nullable: true }
    GeoCoordinates:
        properties:
            latitude: { range: Number }
            longitude: { range: Number }
    PostalAddress:
        properties:
            addressCountry: ~
            addressLocality: ~
            addressRegion: ~
            postalCode: ~
            streetAddress: ~
    Event:
        properties:
            name: ~
            description: ~
            subEvent: ~
            superEvent: ~
            location: { range: Church }
            isAccessibleForFree: ~
            inLanguage: { range: Text }
            startDate: { range: DateTime }
            endDate: { range: DateTime }
            doorTime: ~
            duration: { range: Number }
    OpeningHoursSpecification:
        properties:
            opens: ~
            closes: ~
            dayOfWeek: { range: DayOfWeek }
            validFrom: ~
            validThrough: ~
    DayOfWeek:
        properties:
            name: ~
    Review:
        properties:
            itemReviewed: { range: Church }
            reviewAspect: { range: Text }
            reviewBody: ~
            reviewRating: { range: Number }
