name: Build docker image

on: [workflow_call]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create version.json file
        run: |
          echo "{ \"version\": \"$(git rev-parse --short HEAD)\", \"build\": \"$(date)\", \"branch\": \"$(git rev-parse --abbrev-ref HEAD)\", \"tag\": \"$(git name-rev --tags --name-only $(git rev-parse HEAD))\" } " > public/version.json

      - name: Build and push image
        run: |
          docker build -t hozanaci/openchurch-backend:$(git rev-parse --short HEAD) -f docker/php/Dockerfile .
          docker push hozanaci/openchurch-backend:$(git rev-parse --short HEAD)
          docker build -t hozanaci/openchurch-sync:$(git rev-parse --short HEAD) -f docker/python/Dockerfile .
          docker push hozanaci/openchurch-sync:$(git rev-parse --short HEAD)
          docker build -t hozanaci/openchurch-elasticsearch:$(git rev-parse --short HEAD) -f docker/elasticsearch/Dockerfile .
          docker push hozanaci/openchurch-elasticsearch:$(git rev-parse --short HEAD)

  publish-docker-image:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push latest
        run: |
          docker pull hozanaci/openchurch-backend:$(git rev-parse --short HEAD)
          docker tag hozanaci/openchurch-backend:$(git rev-parse --short HEAD) hozanaci/openchurch-backend:$(git rev-parse --abbrev-ref HEAD)
          docker push hozanaci/openchurch-backend:$(git rev-parse --abbrev-ref HEAD)
          docker pull hozanaci/openchurch-sync:$(git rev-parse --short HEAD)
          docker tag hozanaci/openchurch-sync:$(git rev-parse --short HEAD) hozanaci/openchurch-sync:$(git rev-parse --abbrev-ref HEAD)
          docker push hozanaci/openchurch-sync:$(git rev-parse --abbrev-ref HEAD)
          docker pull hozanaci/openchurch-elasticsearch:$(git rev-parse --short HEAD)
          docker tag hozanaci/openchurch-elasticsearch:$(git rev-parse --short HEAD) hozanaci/openchurch-elasticsearch:$(git rev-parse --abbrev-ref HEAD)
          docker push hozanaci/openchurch-elasticsearch:$(git rev-parse --abbrev-ref HEAD)
